name: Feedback
description: Feedback for code party at RubyKaigi 2025
title: "[RubyKaigi 2025]: Code party feedback"
body:
  - type: markdown
    attributes:
      value: |
        アンドパッド ([@andpad_dev](https://x.com/andpad_dev)) は X (旧 Twitter) で技術情報や採用情報などを発信しています。 ぜひフォローください!

        ANDPAD ([@andpad_dev](https://x.com/andpad_dev)) shares technical information, job openings, and more on X (formerly Twitter). Please be sure to follow them!
  - type: textarea
    id: fun
    attributes:
      label: 楽しかったですか？ / Did you have fun?
      description: |
        楽しかった場合はどういう部分が楽しかったかも教えてください。（例：Ruby書くことそのものが楽しかった、●●のgemの作者とお話できたから、など）

        If you had fun, what kind of part was fun?（e.g. Because I was able to talk with the author of ●●gem, Ruby it was fun to write, etc.）
    validations:
      required: true
  - type: textarea
    id: groups
    attributes:
      label: どのグループに参加しましたか？ / Which groups did you join?
    validations:
      required: true
  - type: textarea
    id: etc
    attributes:
      label: なにか思ったことがあれば自由に書いてください。 / Please give us any feedback.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        宣伝: 5月12日にコード懇親会でやったことや楽しかったことを自慢する「[コード懇親会自慢大会](https://andpad.connpass.com/event/352071/)」を東京のアンドパッドのコミュニティスペースで開催します！オンライン参加もできるので、ぜひ、楽しかったことを他の人にも教えてあげてください！

        There is an after event of this event ["Code Party Boast Party"](https://andpad.connpass.com/event/352071/) on 2025-05-12T19:00:00+0900 at ANDPAD community space in Tokyo. You can join the event as an online or offline speaker/attendee. Let's share what you enjoyed today!
